---
- name: Install PostgreSQL and dependencies
  ansible.builtin.package:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present
  become: yes
  tags: [db, install]

- name: Start and enable PostgreSQL service
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes
  become: yes
  tags: [db, config]

- name: Ensure PostgreSQL is listening on all interfaces
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: "^#?listen_addresses"
    line: "listen_addresses = '*'"
  become: yes
  notify: restart postgresql
  tags: [db, config]

- name: Allow MD5 password authentication from any IP
  community.postgresql.pg_hba:
    dest: /etc/postgresql/14/main/pg_hba.conf
    contype: host
    databases: all
    users: all
    address: '0.0.0.0/0'
    method: md5
    state: present
  become: yes
  notify: restart postgresql
  tags: [db, config]

- name: Create the application database
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    state: present
  become: yes
  become_user: postgres
  tags: [db, config]

- name: Create the application database user
  community.postgresql.postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "ALL"
    state: present
  become: yes
  become_user: postgres
  tags: [db, config]
