- name: Install PostgreSQL server
  ansible.builtin.apt:
    name: postgresql
    state: present
    update_cache: yes
  become: yes
  tags:
    - install
    - db

- name: Ensure PostgreSQL service is running
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: yes
  become: yes
  tags:
    - db

- name: Create database user for app
  community.general.postgresql_user:
    db: postgres
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    state: present
  become: yes
  become_user: postgres
  tags:
    - config
    - db

- name: Create database for app
  community.general.postgresql_db:
    name: "{{ app_name }}_db"
    owner: "{{ db_user }}"
    state: present
  become: yes
  become_user: postgres
  tags:
    - config
    - db

- name: Allow connections from app server (if on a different host)
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    line: "host {{ app_name }}_db {{ db_user }} {{ groups['web_servers'] | map('ansible_host') | join(',') }}/32 md5"
    insertafter: EOF
    state: present
  become: yes
  notify: Restart postgresql
  when: groups['app_servers'] is defined and groups['app_servers'] | length > 0
  tags:
    - config
    - db

- name: Configure PostgreSQL to listen on all interfaces (if needed for remote access)
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    regexp: "^#listen_addresses = 'localhost'"
    line: "listen_addresses = '*'"
    state: present
  become: yes
  notify: Restart postgresql
  tags:
    - config
    - db
