- name: Deploy web and application for staging environment
  hosts: staging
  become: yes
  roles:
    - role_web
    - role_app

- name: Deploy web and application for production environment
  hosts: production
  become: yes
  roles:
    - role_web
    - role_app
