---
- name: restart app
  ansible.builtin.service:
    name: "{{ app_service_name }}"
    state: restarted
  become: yes

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: Restart Gunicorn
  ansible.builtin.systemd:
    name: "gunicorn_{{ app_name }}.service"
    state: restarted
  become: yes
