---
- name: Update apt cache (Debian/Ubuntu)
  ansible.builtin.apt:
    update_cache: yes
  become: yes
  when: ansible_os_family == 'Debian'
  tags:
    - install

- name: Update yum cache (CentOS/RHEL)
  ansible.builtin.yum:
    update_cache: yes
  become: yes
  when: ansible_os_family == 'RedHat'
  tags:
    - install

- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present
  become: yes
  tags:
    - install

- name: Copy Nginx configuration template
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: restart nginx
  tags:
    - config

- name: Ensure Nginx service is running and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  become: yes
  tags:
    - install
